### ISSUE TITLE
Please try to work alongside bandcamp enhancement suite #177

### ISSUE THREAD

**Issue by jrefano** [azarbayejani/bandcamp-tempo-adjust#14] opened 2024-05-24 21:47 UTC
I love both this app and https://github.com/sabjorn/BandcampEnhancementSuite by @sabjorn, but I wish I could use both at the same time.

I wonder if there is some way the two projects could coordinate in some way so that is possible?

Thanks much for a great app!

**Comment by azarbayejani** [comment] 2024-06-06 04:52
Closed as duplicate of #8

**Closed as completed by azarbayejani** 2024-06-06 04:52 UTC
